### ISSUE TITLE
Thoughts on adding longer macro definitions

### ISSUE THREAD

**Issue by Gavinok** [n-t-roff/heirloom-doctools#100]
I really like heirloom troff and was wondering if you are open to the idea of longer macro, string, and register names?.

**Comment by Gavinok** [comment]
I am willing to make the pull request but don't want to go against the goals of the project.

**Comment by Alhadis** [comment]
When you say _"longer macro definitions"_, what exactly are you referring to…?

**Comment by Gavinok** [comment]
My mistake I don't know how I misses this in the docs
