### ISSUE TITLE
Rendering differences with doc

### ISSUE THREAD

**Issue by bapt** [n-t-roff/heirloom-doctools#11]
Hi,

Testing with usd documentation from freebsd I figured out there are some differences with groff generated documentation

The documenation is the following:
https://svnweb.freebsd.org/base/head/share/doc/usd/06.bc/bc?revision=216178&view=markup

I do test rendering it with:
nroff -ms  bc | col -x

In the result I do get the following issues I do not get when rendering with groff:
there is an extra newline between the name of the 2 authors (between .AU lines)
The author names are not "highlighted"
The current date is show at the bottom of each pages where no dates are supposed to be printed
There is an extra line at the bottom of the first page

**Comment by n-t-roff** [comment]
The only bug I can see at first view is that the indentation is wrong in heirloom. The "problems" you mention are just how original ms(7) did format a document.

groff's ms(7) is written from scratch by James Clark (groff developer), without having access to the original AT&T macros (the one which heirloom has). So if there are differences between groff and the AT&T version I am not sure if the original should be changed.

I will look into the indentation problem. But are you really sure you want to discard how original ms(7) did work and introduce the behaviour of a reimplementaion from scratch?

**Comment by bapt** [comment]
Not really, I was just surprised by the rendering differences, to be honnest the only thing that bothers me there is the date added on pages maybe it is a problem in the document and I should fix it, I'm quite new to the roff land :)

**Comment by n-t-roff** [comment]
You can suppress the date with a .ND as (one of) the first macro call(s).

Anyway there is a bug with the left margin which needs to be fixed.

**Comment by n-t-roff** [comment]
The "page offset bug" is actually a document bug. Someone had introduced .po and .ll which is not compatible with ms(7). Even groff does not process the .ll request correctly. Instead of
```
.po 5n
.ll 70n
```
it would be correct to write
```
.nr PO 5n
.nr LL 70n
```
Printing the date is a feature of the original ms(7) which can be switched of with .ND

So the found issues are actually not bugs.

**Comment by bapt** [comment]
Thank you very much and sorry for noise, I have fixed the document
