### ISSUE TITLE
mdoc(7): add support for -nohang in .Bl

### ISSUE THREAD

**Issue by bapt** [n-t-roff/heirloom-doctools#12]
.Bl is missing -nohang support supported by both mandoc and groff, this makes warnings to be issued when rendering the following manpage https://svnweb.freebsd.org/base/head/tools/tools/cxgbetool/cxgbetool.8?view=markup

**Comment by n-t-roff** [comment]
Will be implementet.

**Comment by n-t-roff** [comment]
There had been a bug with restoring the list type at the end of a list. It should work now. (At the moment it is only tested with this manual page. I'll extend the tests to all FreeBSD manual pages in the next days.)

**Comment by bapt** [comment]
I can confirm it works! thank you
