### ISSUE TITLE
rendering differencies with groff

### ISSUE THREAD

**Issue by bapt** [n-t-roff/heirloom-doctools#15]
On the troff documentation:
https://svnweb.freebsd.org/base/head/share/doc/usd/21.troff/
in the file: m0a line 439

With groff the result is a list of of characters blocks separated by space
```
          Alphabetical Request and Section Number Cross Reference
          a20   c10   di7   e18   h13   l10   ne3   os5   r18   ss2   u10
          ad4   c10   ds7   fc9   h13   l10   nf4   p14   rm7   sv5   u10
          af8   ce4   dt7   fi4   i16   ll6   n13   p19   rn7   ta9   vs5
          am7   ch7   e10   f20   i16   ls5   n15   pl3   rr8   tc9   wh7
          as7   cs2   e16   fp2   i20   l14   n15   p20   rs5   ti6
          bd2   c10   em7   ft2   in6   m20   nr8   pn3   rt3   t14
          bp3   da7   e10   fz2   it7   mk3   ns5   po3   s19   t20
          br4   de7   e17   h13   lc9   na4   n19   ps2   sp5   t10
```

With heirloom the result is one block per line with indentation

```
Alphabetical Request and Section Number Cross Reference
a20
ad4
af8
am7
as7
bd2
bp3
br4
     c10
     c10
     ce4
     ch7
     cs2
     c10
     da7
     de7
          di7
          ds7
          dt7
          e10
          e16
          em7
          e10
          e17
               e18
               fc9
               fi4
               f20
               fp2
               ft2
               fz2
               h13
...
```

The command used to render is:
tbl m.mac m0 m0a m1 m2 m3 m4 m5 table1 table2 | nroff

**Comment by n-t-roff** [comment]
You did forget to pipe it through "col -x". This is not necessary with groff but it is for traditional nroff. You need to use heirloom's col(1) (or other capable versions but there might be issues with UTF-8 with other versions). E.g. Linux col(1) seems to totally useless, I don't know about FreeBSD col(1).

I recommend option -Tlocale for both tbl(1) and nroff. So the pipe could be:
```
tbl -Tlocale m.mac m0 m0a m1 m2 m3 m4 m5 table1 table2 | nroff -Tlocale | col -x | less
```
If tbl(1) is used with troff I suggest option -g for tbl(1).

**Comment by bapt** [comment]
erg sorry for noise again
