### ISSUE TITLE
Issues with mdoc(7)

### ISSUE THREAD

**Issue by bapt** [n-t-roff/heirloom-doctools#19]
2 issues have been found when rendering procctl(2) manpage (https://svnweb.freebsd.org/base/head/lib/libc/sys/procctl.2?revision=281887&view=markup) in pdf (actually rendering in terminal show the same issues)

The first one is apparently .Lb is not supported (see LIBRARIES section)

The second is probably more complicated and not sure will be considered as an issue but if you look at the manpage rendered in pdf:
https://www.kib.kiev.ua/kib/procctl.hlrm.pdf vs https://www.kib.kiev.ua/kib/procctl.groff.pdf
search for PROC_TRACE_CTL_ENABLE and you will see groff does a better job with line breaks. (all the same from commandline)

Also note that mandoc has the same issue with line breaks

**Comment by n-t-roff** [comment]
.Lb had been introduced by groff and is not used by OpenBSD so I didn't notice it up to now.

In your groff document non-standard options are used. I generated
```
troff -Tps procctl.2 | grops | ps2pdf - g.pdf
```
with current groff from git and it looks nearly identical to the heirloom document (same fonts, same poor line breaks).

Which command did you use exactly to produce the groff document?
There seems to be a custom tmac file in use to change the font and maybe font size, margins etc. Do you know which custom tmac file is used?
Is the default paper size to generate these documents letter or a4?

**Comment by kostikbel** [comment]
groff was from the FreeBSD stable/10 installation, which declare itself as GNU troff (groff) version 1.19.2.

The commands to generate groff document was:
troff -Tdvi -mdoc  procctl.2 | grodvi >procctl2.dvi
dvipdfm procctl.2.dvi
where dvipdfm came from teTeX 2014, but this is probably irrelevant.

I confirm, with -Tps I get the same ugly line breaks.

**Comment by bapt** [comment]
I see the lack of .Lb support has been fixed, the ps generation as groff so I bet I can juste close this ticket
