### ISSUE TITLE
Characters defined with the .char request do not work when they are the first character following a .nop and may crash the PostScript stack.

### ISSUE THREAD

**Issue by reffort** [n-t-roff/heirloom-doctools#23]
Characters defined with the `.char` request do not work when they are the first character following a `.nop` and may crash the PostScript stack.

Below is sample code using Computer Modern 10 and Adobe Minion.  Most OTF and TTF fonts, and many Type 1 fonts, also lead to a PostScript stack error which causes a blank page in the Evince viewer.  When converting that PS file to PDF both Ghostscript and the Acrobat Distiller exit with a PostScript stack error.

Placing `\&` before the character ( `.nop \&\[char]` ) allows the line to work as expected, but should not be necessary.

Heirloom functions as expected.

Sample output: ![test](http://i.imgur.com/ZuijeHG.png)

This sample uses a char named `\[typo]`, which begins an inline environment, switches to Adobe Minion, prints the `\[tau]` character, pops the previous font (which is not necessary with an inline environment but is included for completeness), and then exits the environment.

The lines of the sample output show:

1. Various methods of printing a `\[tau]` character.  All work with Heirloom.  `.nop \[char]` results in the `.notdef` glyph with n-t-roff.

2. The smartquote macro from the MOM macros, where the straight quote character is redefined using a .char macro sequence to produce curly quotes.  This works as expected in Heirloom but does not work with n-t-roff. (MOM macro not included)

3. A test sequence defined as a string with `.ds` (works).

4. A similar test sequence defined as a character with `.char` (doesn't work with `.nop` in n-t-roff).

5. The `.notdef` glyphs. (Computer Modern does not have a `.notdef` glyph, which would otherwise be printed in the right portion of line 4.  The only font I could find that demonstrates all aspects of this problem and doesn't crash the PostScript stack is a prehistoric version of Iowan Oldstyle in Type 1 format).

6. Standard characters `\[name]` and `\U'#'` work with `.nop`.

```
.fp 0 CMR cmr10 pfb\" cmr10 does not have a tau char
.fp 0 AMR MinionPro-Regular otf\" but Minion does
.
.char \[typo] \@{\f[AMR]\[tau]\fP\@}
.
.ds stest stest\ 123
.char \[ctest] ctest\ 123
.ft CMR
\# Heirloom
\# n-t-roff
.br
1.
\@{\f[AMR]\[tau]\fP\@}
.nop \@{\f[AMR]\[tau]\fP\@}
\[typo]
.nop \[typo]
.nop \&\[typo]
.nop ~a\[typo]\ \ 
.br
2.
.nop "smart" quotes
.br
3.
\*[stest]\ \ \ 
.nop \*[stest]
.br
4.
\[ctest]\ \ \ 
.nop \[ctest]
.br
5.
.nop \&.notdef glyphs:
.br
\f[AMR]\[.notdef] AMR (Minion)\fP
.br
\f[CMR]\[.notdef] CMR (Computer Modern) (none)
.br
6.
.nop \[E]nd of test.
.br
.nop \[emdash]
.nop \[H]ave a nice
.nop \U'0064'ay.
```

**Comment by n-t-roff** [comment]
I noticed something similar yesterday (not before) when preparing doc/troff/doc.tr. I look into this. Note that .char had been implemented the wrong way which had lead to many issues already.

By "Heirloom" you refer to the SourceForge repository?

**Comment by n-t-roff** [comment]
This should be solved now, please synchronize again.

**Comment by reffort** [comment]
Yes, "Heirloom" is the 32-bit code. I'll check this out, thanks.

**Comment by reffort** [comment]
This appears to be fixed.  Thanks!  Applied patch of Aug. 5, 2015, ".char defined chars did not work as first char after .if"
