### ISSUE TITLE
Space not correctly adjusted when line does not end with " \c"

### ISSUE THREAD

**Issue by n-t-roff** [n-t-roff/heirloom-doctools#24]
I did compare the troff output and the PS files with and without " \c" (uising your example from #22). I don't see a difference (using `diff`(1)).

I only have 64 bit hardware. I'll try to set up a 32 bit virtual machine. This may take some time.

**Comment by reffort** [comment]
I see this on the Heirloom code (32-bit code/compiler).  It occurs regardless of whether the compiled code is run on a 32 or 64 bit OS, but I haven't verified it on the n-t-roff 64-bit code (which is the main reason I didn't file a bug report).

**Comment by reffort** [comment]
Ran across this while building the Troff User Manual troff.doc

In section 9.2, the tabular description for **.ta** "Set repeated tab stops" a line does not justify unless a sentence has a [space]\c appended to it.

The line with the red dot is not justified at all.
![ta-before](https://cloud.githubusercontent.com/assets/13387711/9674400/47bbb1dc-5276-11e5-929f-e875ed098805.png)

Appending `[space]\c` to the source line beginning with &
```
.bt
\fB&ta\fI|Mv|...|Nw|\fBT\fI|At|...|Zu\fRa	\fIN\fR=0	E,\fBm\fR\
	Set repeated tab stops and types at \fIMv\fR, ..., \fINw\fR,
\fIN\fR|+|\fIAt\fR, ..., \fIN\fR|+|\fIZu\fR,
\fIN\fR|+|\fIZ\fR|+|\fIAt\fR, ..., \fIN\fR|+|\fIZ\fR|+|\fIZu\fR,
\fIN\fR|+|2·\fIZ\fR|+|\fIAt\fR, ..., \fIN\fR|+|2·\fIZ\fR|+|\fIZu\fR,
\fIN\fR|+|3·\fIZ\fR|+|\fIAt\fR, ..., \fIN\fR|+|3·\fIZ\fR|+|\fIZu\fR,
< old:  &..\ .
> new:  &..\ . \c
Thus \fB&ta|T|0.5i\fR sets tab stops every 0.5in,
and \fB&ta|1i|4i|T|.25i|1i\fR sets tab stops
at 1in, 4in, 4.25in, 5in, 5.25in, 6in, 6.25in, etc.
```

And the line now justifies.
![ta-after](https://cloud.githubusercontent.com/assets/13387711/9674478/1559d9f2-5277-11e5-9116-752d8e5c4b99.png)

**Comment by n-t-roff** [comment]
I can't verify this. Did you modify `doc/troff/doc.tr`? What I do is
```bash
cd doc/troff
make clean doc.pdf
```
Then "Thus" in `doc.pdf` is flush right.

**Comment by n-t-roff** [comment]
Could it be possible that the problem only occurs when something is printed in the page margin?
Normally I don't have your patch active, maybe that's why I don't see this issue.

Do you see the problem when you generate the document with current repository version? That would be one way to reproduce it.

Did you this time use a 64 bit hardware? And also a 64 bit OS (compiler)? Do you use `gcc`?

**Comment by reffort** [comment]
The numbers that print in the margin were actually turned off at the time I noticed that the line didn't justify (there's a .spreadmark request to switch them on and off).  I turned the numbers on to see if that was actually the case and to see how bad the space size really was.

The way the margin character feature is implemented in troff, it just spaces over from wherever the line ends, it doesn't try to align the margin chars vertically; so if the margin chars are off like that, that's a confirmation that the line didn't spread.

Looking at that area of the code, I didn't see anything with the spreadmark lines that should cause a problem, especially when it is turned off, but I'll poke around in there next time I compile troff.

The files are dated July 7, and there is one fix for .char patched into it.  Git doesn't provide any mechanism to identify file versions that I am aware of.

(Btw, do any of the subsequent patches fix .char when used with \w, as in `\w'\[adotchar]'`?  With the 7/7 code it returns the space width, which means the character was not found.)

I'm running Mint 17.1 64.  The output of gcc -v is:
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
[lots of config things]
Thread model: posix
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04) 
```

**Comment by n-t-roff** [comment]
For the ".char used with \w'\[<special_char_name>]'" I have created the new issue #28 to not mix several topics.

**Comment by n-t-roff** [comment]
Is there an unpatched version (without your code) which shows the issue with doc/troff/doc.tr so that I can directly reproduce it? It would be good to have a "list of instructions" (e.g. use version ..., cd doc/troff, make doc.pdf) with which the issue can be reproduced. I don't think that OS or compiler is the cause as long as everything is 64 bit.

You get the project version with `git log`. The top hash ID is the version then.

To get a file version you can use `git log` &lt;*filename*&gt;. To get the version of a code line use `git blame -L` &lt;*line*&gt; &lt;*file*&gt;.

**Comment by reffort** [comment]
Have reproduced the problem outside of doc.tr and can confirm that it is still a problem with the current build.

Five conditions must occur:
1. There is a sentence space (a period at the end of an input line).
2. There is exactly one word following the sentence space on the output line.
3. There is at least one non-standard space preceding the sentence space on the same output line.  Non-standard spaces include: unpaddable space `\_` ; a tie, `\~` ; digit-width space, `\0` ; spaces resulting from .tr, such as `.tr |`(eol) as used in doc.tr.  There may well be other cases that result from .char, .ds, etc.
4. Non-zero sentence space size (e.g., the default `.ss 12` or a user-defined size such as `.ss 12 6`).
5. Minimum space size is less than the word space size (e.g., `.minss 8`).

If these conditions occur on the first output line, the tab positions are also incorrect.

Four of the five conditions are active in the paragraph from doc.tr I showed previously.  To show the problem just insert `.minss 8` following the .bt call at line 4347.

The problem goes away when the sentence space is turned off, by adding `\&` after the period at the end of the input line, or by inserting `.ss 12 0` before the paragraph text, or with ` \c` as shown previously. `\p` causes the lines to extend beyond the end of the margin.

```
.bt
\#.ss 12 0
\#.ss 12 6
.minss 8
\fB&ta (etc).
[ . . . Set repeated tab stops . . . ]
\#&..\ .\&
\#Thus\p
```

The requirement of having exactly one word following the sentence space is reminiscent of the problem that occurred with input line breaks within the sentence, necessitating the use of  ` \c` to have uniform word spaces with multiple input lines.  The word space in the output line that followed the line break in the input line was the dividing point between different space sizes to the left and to the right.

.char is still broken with '\w' as shown in the PDF below.

The current version of doc.tr throws numerous "missing glyph" errors and prints spurious lines to the terminal.

PDF of space problems:
[ssbugs.pdf](https://github.com/n-t-roff/heirloom-doctools/files/46751/ssbugs.pdf)

**Comment by n-t-roff** [comment]
I could only reproduce it with inserting .minss 8 into doc.tr. Creating a minimum test file did not work. Could you please test if there is some regression with the latest commit especially regarding .minss?

**Comment by n-t-roff** [comment]
Issue assumed to be solved.
