### ISSUE TITLE
.char used with \w'\[<special_char_name>]'

### ISSUE THREAD

**Issue by n-t-roff** [n-t-roff/heirloom-doctools#28]
(Issue mentioned in #24 by @reffort: Do any of the subsequent patches fix .char when used with \w, as in \w'\[adotchar]'? With the 7/7 code it returns the space width, which means the character was not found.)

Could you please give a short example (two code lines) with the use of `.char` and `\w`?  What means 7/7--July 7th?

**Comment by reffort** [comment]
Slightly more than two lines, but

```
.nr wblt \w'\(em'
.tm width of \(em is \n[wblt]
.char \[charem] \(em
.nr wblt \w'\[charem]'
.tm width of \[charem] is \n[wblt]
```

The width of `\(em` returns 10000 and the width of `\[charem]` returns 3330 with `.ps 10` with texgyretermes (size of the em dash varies with the font). There's a sample on the third page of the PDF I uploaded under "Space not correctly adjusted . . . "\c"

This also causes tbl to incorrectly calculate column widths when there are .chars (it uses `\w` to do that).

version.mk reads "Git snapshot 150629" but this also occurs with the current build.  (I do not know any way to identify a version of the files themselves.)

**Comment by n-t-roff** [comment]
This should work now. As said .char is not correctly implemented. For man pages it had been important to use .char for `'`. With this e.g. `\w'`...`'` did not work anymore. Fixing this without completely reimplementing .char is kind of tinkering.

Git: If you have only the files without the .git repository it is IMHO not possible to identify the version. With the repository you can use e.g. `git log` of course.

**Comment by n-t-roff** [comment]
Closing solved issue.
