### ISSUE TITLE
hardcoded path in manpages

### ISSUE THREAD

**Issue by bapt** [n-t-roff/heirloom-doctools#35]
Lots of manpages are referring to hardcode path for files

Maybe those should be renamed .in and sed could fix those path?

**Comment by n-t-roff** [comment]
Of course. I'll check these manpages.

**Comment by n-t-roff** [comment]
I did fix those I've found. One did use the full path of `sort`(1). I did use &grave;`which sort`&grave; for `sed`, but maybe `.Xr sort 1` would have been better.
