### ISSUE TITLE
eqn dies on "bizzare" characters delimiter

### ISSUE THREAD

**Issue by bapt** [n-t-roff/heirloom-doctools#43]
https://svnweb.freebsd.org/base/head/share/doc/papers/timecounter/timecounter.ms?revision=160964&view=markup#l2

```
.EQ
delim øø
.EN
```

In this document it is in ISO-8859 but if I change it to UTF-8 it still dies the same

**Comment by bapt** [comment]
seems like it is not multibyte friendly

**Comment by n-t-roff** [comment]
Non-ASCII delimiters are a general Heirloom doctools issue, not for eqn only. Whereas the crash is not acceptable and may be fixed quickly, correct processing of such characters may require more effort (without looking at the source code yet). Currently I'm preparing a release of another project (may take one or two weeks). What is your expected fix date for this issue?

**Comment by bapt** [comment]
Crash was a strong word, it is failing reporting an error :)
