### ISSUE TITLE
A possible problem with .lsm request...

### ISSUE THREAD

**Issue by aksr** [n-t-roff/heirloom-doctools#69]
I think there's a problem with how `.lsm` works.
E.g. after `.lsm test`, text part `1.` doesn't get bold while everything else is:

    .do xflag 3
    .sp 5
    .de test
    . ft B
    . br
    ..
    Ab odio enim unde cum.  
    .sp
    .lsm test
     1. Itaque eos corrupti hic fugit laboriosam numquam.
     2. Itaque eos corrupti hic fugit laboriosam numquam.
     3. Itaque eos corrupti hic fugit laboriosam numquam.
     4. Itaque eos corrupti hic fugit laboriosam numquam.
    .sp
    Vel sunt excepturi non tenetur et vitae et.

**Comment by n-t-roff** [comment]
This is yet another prefetch issue. Could you please test the committed change?

**Comment by aksr** [comment]
It seems it's fixed now.

**Comment by aksr** [comment]
I'll test this further. For now, it seems fixed, therefore closing...
