### ISSUE TITLE
Whitespace is significant inside \D'...'

### ISSUE THREAD

**Issue by nbuwe** [n-t-roff/heirloom-doctools#73]
troff seems to insist on parameters inside \D'...' separated with exactly one space.  This precludes visual alignment in code like, e.g.:
```
\" 60 degrees segment on the left
\D'l -.87i -.5i'\
\D'a  .87i  .5i \
     -.87i  .5i'\
\D'l  .87i -.5i'
```
which, arguably, makes it a bit more readable.

It would be nice to support flexible whitespace here (groff does).

**Comment by n-t-roff** [comment]
Thank you for reporting.
