### ISSUE TITLE
Constant-width fonts are messed up if paragraph crosses page boundaries

### ISSUE THREAD

**Issue by LeonardKoenig** [n-t-roff/heirloom-doctools#78]
Edit: Nevermind, after hours of debugging: It was just a typo, my bad.

----------------

I've observed the behavior that if one paragraph crosses the boundary of a page, selecting the constant-width fonts is not working correctly.
Here's a test file: [test.pdf](https://github.com/n-t-roff/heirloom-doctools/files/2473840/test.pdf), it only contains the line

```roff
foo \f(CRbar(1)\fP
```
all over again.

To show the difference between one line on the first page and one on the second, I made to screenshots:
![first page](https://user-images.githubusercontent.com/7831843/46881683-89d3de00-ce4c-11e8-89c5-5b3194c8d009.png)
![second page](https://user-images.githubusercontent.com/7831843/46881687-8b9da180-ce4c-11e8-9ec8-242a227c5cd9.png)

Setting `.do xflag 3` does not change the behavior.

I'm running latest git (6fa0ad8) heirloom troff on Arch using:
```sh
$ /usr/heirloom/bin/ucb/troff -Tpost test.roff | /usr/heirloom/bin/ucb/dpost | ps2pdf - test.pdf
```

Thanks for this awesome work though!

**Comment by LeonardKoenig** [comment]
However with `\fCW` I didn't have any issues in the first place for some reason. Or perhaps a paragraph just moved in a way that it looked like it, I thought the issue was on my side.

**Comment by n-t-roff** [comment]
Sorry, the commit message went wrong, I did use @Leonard instead of @LeonardKoenig ... Not easy to fix since commit is pushed already...

It does work for CW since no font name mapping needs to be applied for CW (it is the original name), but CR needs to be mapped to CW... This had been done at document start but not after a page break.

**Comment by Alhadis** [comment]
> Not easy to fix since commit is pushed already...

It's not too late to force-push an amended commit, is it?

~~~console
$ git commit --amend
…
$ git push origin master --force
~~~

**Comment by LeonardKoenig** [comment]
Ah, that makes sense, thanks for explaining!

No problem, perhaps the other guy might wonder why they get notified, though. Rewriting something officially pushed is not so good, but it's not that late, but don't bother for me.

**Comment by n-t-roff** [comment]
@Alhadis thank you, applied.
